### ISSUE TITLE
关于scratch3.0生成python代码的问题

### ISSUE THREAD

**Issue by ZhaoShuaifei123** [wwj718/blockly_dev#1]
您好，看到您的博客上说有一个从Scratch3.0的积木中生成Python代码的示例（wwj718/blockly_dev scratch-blocks_hello_world），想问一下这个项目可以运行吗？能否告知一下配置环境、运行的步骤？谢谢了。

**Comment by wwj718** [comment]
目前只做过这个简单探索： https://github.com/wwj718/blockly_dev/tree/master/src/scratch-blocks_hello_world
