### ISSUE TITLE
在scratch3.0中 generator code问题的请教

### ISSUE THREAD

**Issue by zy0228** [wwj718/blockly_dev#3]
我想尝试在scratch上拖动积木块生成pyhton
有以下几个问题：
1 python_compressed.js 这份文件我应该在scratch-blockls中如何引入
2 Blockly.Python[' xxx '] 这部分代码 我应该要写在scratch-blocks/blocks_vertical/xxx.js 中吗
3 官方的blockly的workspace生成代码是Blockly.Python.workspaceToCode(workspace);而我要在scratch-gui中怎么获取到

**Comment by wwj718** [comment]
hi 你好，我没在Scratch上generator code，对此没经验，恐怕帮不上什么忙

只做过这个简单实验： https://github.com/wwj718/blockly_dev/tree/master/src/scratch-blocks_hello_world
